networking_api_forms:
    type: rest
    prefix: /admin/cms/api
    resource: "Networking\\FormGeneratorBundle\\Controller\\FormAdminController"

networking_form_view:
    path: /view_form/{id}
    defaults: { _controller: "NetworkingFormGeneratorBundle:FrontendForm:viewForm"}

